
export enum Page {
  Home = 'Home',
  GroupOverview = 'GroupOverview',
  MotrexDetail = 'MotrexDetail',
  MotrexEvDetail = 'MotrexEvDetail',
  MotrexEfmDetail = 'MotrexEfmDetail',
  MtrDetail = 'MtrDetail',
  JunjinDetail = 'JunjinDetail',
  TailoredInCabin = 'TailoredInCabin',
  SvmDetail = 'SvmDetail',
  Innovation = 'Innovation',
  EzCockpitDetail = 'EzCockpitDetail',
  NidusDetail = 'NidusDetail',
  AirPurifierDetail = 'AirPurifierDetail',
  SevenInchAvDetail = 'SevenInchAvDetail',
  TaxiPbvAvntDetail = 'TaxiPbvAvntDetail',
  CommercialTruckClusterDetail = 'CommercialTruckClusterDetail',
  TrainVodDetail = 'TrainVodDetail',
  RoofMonitorDetail = 'RoofMonitorDetail',
  CeilingFoldingMonitorDetail = 'CeilingFoldingMonitorDetail',
  HmiDisplayDetail = 'HmiDisplayDetail',
  DsmDetail = 'DsmDetail',
  EvHomeChargerDetail = 'EvHomeChargerDetail',
  PortableChargerDetail = 'PortableChargerDetail',
  Cv1DrtAiAssistantDetail = 'Cv1DrtAiAssistantDetail',
  SeedsDetail = 'SeedsDetail',
  InCabinAdventureDetail = 'InCabinAdventureDetail',
  VisionAiPbvDetail = 'VisionAiPbvDetail',
  AdsPlatformDetail = 'AdsPlatformDetail',
  DashcamDetail = 'DashcamDetail',
  ClusterDetail = 'ClusterDetail',
  Mh300lDetail = 'Mh300lDetail',
  PassengerRseDetail = 'PassengerRseDetail',
  HvacControlDetail = 'HvacControlDetail',
  Contact = 'Contact',
}
